### ISSUE TITLE
Re-use eigenvalue/-vector storage arrays in RawEigenvalue.doDecomposeGeneral when applicable

### ISSUE THREAD

**Issue by hanslovsky** [optimatika/ojAlgo#33]
Currently, `Vt`, `e`, and `d` are created as new instances for every call to `RawEigenvalue.doComposeGeneral`:
https://github.com/optimatika/ojAlgo/blob/master/src/org/ojalgo/matrix/decomposition/RawEigenvalue.java#L1060-L1062
Creating new instances could be avoided by re-using these objects when applicable, i.e. matrix dimensions do not change.
As far as I can tell that would require an additional member variable to store the `double[][]` that is referenced by `Vt` in `doDecomposeGeneral`.

**Comment by apete** [comment]
Done + a couple of other minor improvements. Please verify everything still works.

**Comment by hanslovsky** [comment]
Just pulled the current master and confirmed that I still get the correct result. Thank you for your swift reaction to this request.

**Comment by apete** [comment]
It will be some weeks before a new ojAlgo release - second half of April is my best guess.

**Comment by hanslovsky** [comment]
There is no need for rush here, imglib/imglib2-algorithm#29 is not urgent, so I do not mind waiting for that release.
